<?php

declare(strict_types=1);

namespace Leaf\Console;

use Leaf\Sprout\Command;

class ContextCommand extends Command
{
    protected $signature = 'context
        {--raw? : Print raw .leaf/CONTEXT.md without compacting it}
        {--path= : Project directory to inspect}';

    protected $description = 'Print compact project context for external AI assistants (beta)';

    protected function handle(): int
    {
        $directory = $this->findProjectRoot($this->option('path') ?: getcwd());

        if (!$directory) {
            $this->writeln('<error>No Leaf project found. Run this command from a project with composer.json or .leaf/CONTEXT.md.</error>');

            return 1;
        }

        $contextFile = $this->findContextFile($directory);
        $memory = null;

        if ($contextFile) {
            $memory = file_get_contents($contextFile);

            if ($memory === false) {
                $this->writeln("<error>Could not read $contextFile.</error>");

                return 1;
            }

            if ($this->option('raw')) {
                $this->writeln(rtrim($memory));

                return 0;
            }
        } elseif ($this->option('raw')) {
            $this->writeln('<error>No .leaf/CONTEXT.md file found to print.</error>');

            return 1;
        }

        $this->writeln($this->buildHandoff($directory, $memory, $contextFile));

        // a banner would pollute the handoff people paste into assistants,
        // so the beta note rides as a trailing markdown comment instead
        $this->writeln('<!-- generated by `leaf context` (beta). Wrong or missing context? https://github.com/leafsphp/cli/issues/new -->');

        return 0;
    }

    /**
     * The handoff is fundamentally different from .leaf/CONTEXT.md. The
     * shared context file holds what code cannot say: goals, decisions,
     * reasoning. This command generates the mechanical map the file
     * deliberately leaves out — routes, modules, models, structure —
     * by scanning the project, then appends the shared memory so an
     * external assistant receives both halves in one paste.
     */
    protected function buildHandoff(string $directory, ?string $memory, ?string $contextFile): string
    {
        $projectName = $this->projectName($directory);
        $appType = $this->detectAppType($directory);
        $modules = $this->detectLeafModules($directory);
        $entryPoints = $this->detectEntryPoints($directory);
        $frontend = $this->detectFrontendStack($directory);
        $folders = $this->detectImportantFolders($directory);
        $routes = $this->extractRoutes($directory);
        $models = $this->detectModels($directory);
        $schemas = $this->detectSchemaFiles($directory);
        $envKeys = $this->detectEnvKeys($directory);

        $sections = [];

        $sections[] = trim(<<<MARKDOWN
# Leaf Context Handoff

Project: {$projectName}
App type: {$appType}

Generated from the project by `leaf context`. The mechanical map below is scanned from the code; the shared memory section (when present) carries the project's goals and decisions. Together they replace direct project access for an external assistant.
MARKDOWN);

        $sections[] = trim(<<<MARKDOWN
## Project map

- Entry points: {$this->formatList($entryPoints, 'none detected')}
- Leaf modules: {$this->formatList($modules, 'none detected')}
- Frontend stack: {$this->formatList($frontend, 'not detected')}
- Folders: {$this->formatList($folders, 'no conventional app folders detected')}
MARKDOWN);

        $sections[] = "## Routes\n\n" . ($routes !== ''
            ? $routes
            : '- No routes detected. Route files may use patterns this scan does not recognize — ask the user to share them.');

        if (!empty($models) || !empty($schemas)) {
            $sections[] = trim(<<<MARKDOWN
## Data layer

- Models: {$this->formatList($models, 'none')}
- Schema files: {$this->formatList($schemas, 'none')}
MARKDOWN);
        }

        if (!empty($envKeys)) {
            $sections[] = "## Environment keys (names only, values never leave the machine)\n\n" . implode(', ', $envKeys);
        }

        if ($memory !== null && $contextFile !== null) {
            $source = $this->relativePath($directory, $contextFile);
            $body = $this->compactMarkdown($memory);

            $sections[] = trim(<<<MARKDOWN
## Shared memory ({$source})

{$body}
MARKDOWN);
        } else {
            $sections[] = '## Shared memory' . "\n\n" . 'No `.leaf/CONTEXT.md` found. Agents working inside this project should create one in the leaf.context v1 format and record goals and decisions there.';
        }

        $sections[] = trim(<<<MARKDOWN
## Notes for the assistant

- Treat this handoff as read-only. Agents running inside the project should read `.leaf/CONTEXT.md` directly, inspect the filesystem, and write useful knowledge back to the shared context when they finish.
- Ask the user for any file a change depends on that is not represented here.
MARKDOWN);

        return implode("\n\n---\n\n", $sections);
    }

    protected function findProjectRoot(string $path): ?string
    {
        $directory = realpath($path);

        if (!$directory) {
            return null;
        }

        if (is_file($directory)) {
            $directory = dirname($directory);
        }

        while ($directory && $directory !== dirname($directory)) {
            if (file_exists("$directory/composer.json") || $this->findContextFile($directory)) {
                return $directory;
            }

            $directory = dirname($directory);
        }

        return null;
    }

    protected function findContextFile(string $directory): ?string
    {
        foreach (['CONTEXT.md', 'context.md'] as $file) {
            $path = "$directory/.leaf/$file";

            if (is_file($path)) {
                return $path;
            }
        }

        return null;
    }

    /**
     * Scan route files and pull out actual route registrations, in file
     * order so group/mount context reads naturally.
     */
    protected function extractRoutes(string $directory): string
    {
        $files = [];

        foreach (glob("$directory/app/routes/*.php") ?: [] as $file) {
            $files[] = $file;
        }

        foreach (['routes/index.php', 'routes/web.php', 'routes/api.php', 'index.php'] as $candidate) {
            if (is_file("$directory/$candidate")) {
                $files[] = "$directory/$candidate";
            }
        }

        $output = [];

        foreach (array_unique($files) as $file) {
            $content = file_get_contents($file) ?: '';
            $lines = $this->extractRoutesFromSource($content);

            if (empty($lines)) {
                continue;
            }

            $output[] = '`' . $this->relativePath($directory, $file) . '`';

            foreach ($lines as $line) {
                $output[] = "- $line";
            }

            $output[] = '';
        }

        return trim(implode("\n", $output));
    }

    /**
     * @return string[]
     */
    protected function extractRoutesFromSource(string $content): array
    {
        $routes = [];
        $pattern = '/app\(\)\s*->\s*(get|post|put|patch|delete|options|all|match|view|redirect|resource|apiResource|group|mount)\s*\(\s*([\'"])((?:\\\\.|(?!\2).)*)\2\s*(,)?/';

        if (!preg_match_all($pattern, $content, $matches, PREG_OFFSET_CAPTURE | PREG_SET_ORDER)) {
            return $routes;
        }

        foreach ($matches as $index => $match) {
            $method = strtolower($match[1][0]);
            $firstArg = $match[3][0];

            // the tail is only this call's remaining arguments: clamp it at
            // the next registration so handlers never bleed across routes
            $tailStart = $match[0][1] + strlen($match[0][0]);
            $tailEnd = isset($matches[$index + 1]) ? $matches[$index + 1][0][1] : $tailStart + 160;
            $tail = substr($content, $tailStart, min(160, max(0, $tailEnd - $tailStart)));

            switch ($method) {
                case 'group':
                case 'mount':
                    $routes[] = "GROUP {$firstArg} — routes below this line sit under the prefix";

                    break;

                case 'match':
                    // first arg is the method list, the path comes next
                    if (preg_match('/^\s*([\'"])((?:\\\\.|(?!\1).)*)\1/', $tail, $pathMatch)) {
                        $routes[] = strtoupper($firstArg) . " {$pathMatch[2]} → " . $this->describeHandler(substr($tail, strlen($pathMatch[0])));
                    }

                    break;

                case 'view':
                    $routes[] = "GET {$firstArg} → " . $this->describeSecondString($tail, 'view');

                    break;

                case 'redirect':
                    $routes[] = "GET {$firstArg} → " . $this->describeSecondString($tail, 'redirect');

                    break;

                case 'resource':
                case 'apiresource':
                    $label = $method === 'resource' ? 'RESOURCE' : 'API RESOURCE';
                    $routes[] = "{$label} {$firstArg} → " . $this->describeSecondString($tail, 'controller');

                    break;

                default:
                    $routes[] = strtoupper($method) . " {$firstArg} → " . $this->describeHandler($tail);
            }
        }

        return $routes;
    }

    protected function describeHandler(string $tail): string
    {
        $handler = 'closure';

        if (preg_match('/([\'"])([A-Za-z0-9_\\\\]+@[A-Za-z0-9_]+)\1/', $tail, $match)) {
            $handler = $match[2];
        }

        if (preg_match('/[\'"]middleware[\'"]\s*=>\s*([\'"])((?:\\\\.|(?!\1).)*)\1/', $tail, $match)) {
            $handler .= " [middleware: {$match[2]}]";
        }

        if (preg_match('/[\'"]name[\'"]\s*=>\s*([\'"])((?:\\\\.|(?!\1).)*)\1/', $tail, $match)) {
            $handler .= " [name: {$match[2]}]";
        }

        return $handler;
    }

    protected function describeSecondString(string $tail, string $label): string
    {
        if (preg_match('/^\s*,?\s*([\'"])((?:\\\\.|(?!\1).)*)\1/', $tail, $match)) {
            return "{$label}:{$match[2]}";
        }

        return $label;
    }

    /**
     * @return string[]
     */
    protected function detectModels(string $directory): array
    {
        $models = [];

        foreach (glob("$directory/app/models/*.php") ?: [] as $file) {
            $name = basename($file, '.php');

            // the generated base class is scaffolding, not a model
            if ($name === 'Model') {
                continue;
            }

            $models[] = $name;
        }

        sort($models);

        return $models;
    }

    /**
     * @return string[]
     */
    protected function detectSchemaFiles(string $directory): array
    {
        $schemas = [];

        foreach (glob("$directory/app/database/*.yml") ?: [] as $file) {
            $schemas[] = basename($file);
        }

        sort($schemas);

        return $schemas;
    }

    /**
     * Env key NAMES only. Values never appear in a handoff.
     *
     * @return string[]
     */
    protected function detectEnvKeys(string $directory): array
    {
        $keys = [];

        foreach (['.env.example', '.env'] as $candidate) {
            $file = "$directory/$candidate";

            if (!is_file($file)) {
                continue;
            }

            foreach (explode("\n", file_get_contents($file) ?: '') as $line) {
                if (preg_match('/^([A-Z][A-Z0-9_]*)\s*=/', trim($line), $match)) {
                    $keys[] = $match[1];
                }
            }

            break; // prefer .env.example; fall back to .env only when it is missing
        }

        return array_values(array_unique($keys));
    }

    /**
     * Compact markdown while preserving code fences and nested list indentation.
     */
    protected function compactMarkdown(string $content): string
    {
        $content = str_replace(["\r\n", "\r"], "\n", $content);
        $content = preg_replace('/<!--.*?-->/s', '', $content) ?? $content;

        $lines = explode("\n", $content);
        $filtered = [];
        $blankLines = 0;
        $inFence = false;

        foreach ($lines as $line) {
            $trimmed = trim($line);

            if (!$inFence && $this->isPlaceholderLine($trimmed)) {
                continue;
            }

            if (preg_match('/^\s*```/', $line)) {
                $inFence = !$inFence;
                $filtered[] = rtrim($line);
                $blankLines = 0;

                continue;
            }

            if ($inFence) {
                $filtered[] = rtrim($line);

                continue;
            }

            if ($trimmed === '') {
                $blankLines++;

                if ($blankLines > 1) {
                    continue;
                }

                $filtered[] = '';

                continue;
            }

            $blankLines = 0;
            $filtered[] = rtrim($line);
        }

        return trim(implode("\n", $filtered));
    }

    protected function isPlaceholderLine(string $line): bool
    {
        // official leaf.context v1 rule: a line wrapped in underscores is a
        // template placeholder (optionally sitting inside a list bullet)
        $bare = preg_replace('/^[*-]\s+/', '', $line) ?? $line;

        if (preg_match('/^_[^_].*_$/', $bare) === 1) {
            return true;
        }

        // legacy bracket placeholders from pre-v1 context files
        $line = strtolower($line);

        return str_starts_with($line, '[track your recent changes')
            || str_starts_with($line, '[remove this line')
            || str_starts_with($line, '[add decisions')
            || str_starts_with($line, '[add notes');
    }

    protected function projectName(string $directory): string
    {
        $composer = $this->composerData($directory);

        return $composer['name'] ?? basename($directory);
    }

    protected function detectAppType(string $directory): string
    {
        if (is_dir("$directory/app/console")) {
            return 'Leaf console app';
        }

        if (is_dir("$directory/app/controllers") && is_dir("$directory/app/routes")) {
            return is_dir("$directory/app/views") ? 'Leaf MVC app' : 'Leaf MVC API app';
        }

        if (file_exists("$directory/public/index.php") && file_exists("$directory/leaf")) {
            return 'Leaf MVC-style app';
        }

        if (file_exists("$directory/index.php")) {
            return 'Leaf lite app';
        }

        return 'Leaf app';
    }

    /**
     * @return string[]
     */
    protected function detectLeafModules(string $directory): array
    {
        $composer = $this->composerData($directory);
        $requires = array_merge($composer['require'] ?? [], $composer['require-dev'] ?? []);
        $modules = [];

        foreach ($requires as $package => $version) {
            if (str_starts_with((string) $package, 'leafs/')) {
                $modules[] = "$package ($version)";
            }
        }

        sort($modules);

        return $modules;
    }

    /**
     * @return string[]
     */
    protected function detectEntryPoints(string $directory): array
    {
        return $this->existingPaths($directory, [
            'index.php',
            'public/index.php',
            'leaf',
            'leaf.php',
            'bin/sprout',
        ]);
    }

    /**
     * @return string[]
     */
    protected function detectImportantFolders(string $directory): array
    {
        return $this->existingPaths($directory, [
            'app',
            'app/controllers',
            'app/models',
            'app/views',
            'app/routes',
            'app/database',
            'config',
            'public',
            'storage',
            'tests',
        ]);
    }

    /**
     * @return string[]
     */
    protected function detectFrontendStack(string $directory): array
    {
        $stack = [];

        if (file_exists("$directory/vite.config.js") || file_exists("$directory/vite.config.ts")) {
            $stack[] = 'Vite';
        }

        if (file_exists("$directory/tailwind.config.js") || file_exists("$directory/tailwind.config.ts")) {
            $stack[] = 'Tailwind CSS';
        }

        $packageFile = "$directory/package.json";

        if (is_file($packageFile)) {
            $package = json_decode(file_get_contents($packageFile) ?: '', true) ?: [];
            $dependencies = array_merge($package['dependencies'] ?? [], $package['devDependencies'] ?? []);

            foreach ([
                'react' => 'React',
                'vue' => 'Vue',
                'svelte' => 'Svelte',
                '@inertiajs/inertia' => 'Inertia',
                '@inertiajs/react' => 'Inertia React',
                '@inertiajs/vue3' => 'Inertia Vue',
                '@inertiajs/svelte' => 'Inertia Svelte',
            ] as $packageName => $label) {
                if (array_key_exists($packageName, $dependencies)) {
                    $stack[] = $label;
                }
            }
        }

        return array_values(array_unique($stack));
    }

    /**
     * @return string[]
     */
    protected function existingPaths(string $directory, array $paths): array
    {
        $found = [];

        foreach ($paths as $path) {
            if (file_exists("$directory/$path")) {
                $found[] = $path;
            }
        }

        return $found;
    }

    /**
     * @return array<string, mixed>
     */
    protected function composerData(string $directory): array
    {
        $composerFile = "$directory/composer.json";

        if (!is_file($composerFile)) {
            return [];
        }

        $data = json_decode(file_get_contents($composerFile) ?: '', true);

        return is_array($data) ? $data : [];
    }

    protected function relativePath(string $root, string $path): string
    {
        $root = rtrim(str_replace('\\', '/', $root), '/');
        $path = str_replace('\\', '/', $path);

        if (str_starts_with($path, "$root/")) {
            return substr($path, strlen($root) + 1);
        }

        return $path;
    }

    protected function formatList(array $items, string $fallback): string
    {
        return !empty($items) ? implode(', ', $items) : $fallback;
    }
}
