<?php

declare(strict_types=1);

namespace Leaf\Console;

use Leaf\FS\Directory;
use Leaf\Sprout\Command;

/**
 * Leaf Up Command
 *
 * Scales a lite/basic Leaf app into a full MVC structure.
 *
 * First run: generates .leaf/migration.yml describing the planned changes.
 * Second run: applies those changes.
 */
class UpCommand extends Command
{
    protected $signature = 'up
        {--force? : Apply migration without interactive confirmation}
        {--dry-run? : Show what would be changed without modifying any files}';

    protected $description = 'Scale your Leaf app into MVC structure';

    /** @var string */
    protected string $directory = '';

    protected function handle(): int
    {
        $this->directory = getcwd();
        $leafDir = "{$this->directory}/.leaf";
        $migrationFile = "$leafDir/migration.yml";

        if (!file_exists("{$this->directory}/composer.json")) {
            $this->writeln('<error>No composer.json found. Run this command from the root of a Leaf project.</error>');
            return 1;
        }

        if ($this->isMvcProject()) {
            $this->writeln('<info>✅  Your project is already using Leaf MVC structure. Nothing to scale.</info>');
            return 0;
        }

        if (!file_exists($migrationFile)) {
            return $this->generateMigrationPlan($leafDir, $migrationFile);
        }

        return $this->applyMigration($migrationFile);
    }

    protected function generateMigrationPlan(string $leafDir, string $migrationFile): int
    {
        if (!is_dir($leafDir)) {
            Directory::create($leafDir);
        }

        $moves = $this->detectFileMoves();
        $movesYaml = '';

        foreach ($moves as $from => $to) {
            $movesYaml .= "  - from: $from\n    to:   $to\n";
        }

        if (empty($movesYaml)) {
            $movesYaml = "  [] # No existing files detected to move\n";
        }

        $yaml = <<<YAML
# Leaf Migration Plan — generated by `leaf up`
# -----------------------------------------------
# Edit this file before running `leaf up` again to customise what changes are made.
# Paths are relative to the project root.

# ── Directories to create ────────────────────────────────────────────────────
directories:
  - app/controllers
  - app/models
  - app/views
  - app/routes
  - app/database/migrations
  - app/database/seeds
  - public/assets

# ── Files to move ────────────────────────────────────────────────────────────
# from: current path   to: new path
moves:
$movesYaml
# ── Route extraction ─────────────────────────────────────────────────────────
# When true, routes defined inline in index.php are extracted to app/routes/index.php
# and index.php is rewritten to load them.
extract_routes: true

# ── MVC scaffold ─────────────────────────────────────────────────────────────
# When true, a HomeController stub is created under app/controllers.
scaffold_controller: true

# ── AI context ───────────────────────────────────────────────────────────────
# When true, .leaf/context.md is generated (or updated) with an MVC summary.
generate_ai_context: true

# ── Composer packages ─────────────────────────────────────────────────────────
# Additional Leaf modules to install as part of the migration.
install_packages: []
YAML;

        file_put_contents($migrationFile, $yaml);

        $this->writeln('');
        $this->writeln('<info>✨  Migration plan generated: .leaf/migration.yml</info>');
        $this->writeln('');
        $this->writeln('   Review or customise the plan, then run <comment>leaf up</comment> again to apply it.');
        $this->writeln('');

        if (!empty($moves)) {
            $this->writeln('   Detected files that will be moved:');
            foreach ($moves as $from => $to) {
                $this->writeln("     <comment>$from</comment>  →  <info>$to</info>");
            }
            $this->writeln('');
        }

        return 0;
    }

    /**
     * Detect obvious file moves for a standard lite Leaf app.
     *
     * @return array<string,string>  from → to pairs
     */
    protected function detectFileMoves(): array
    {
        $moves = [];
        $dir = $this->directory;

        foreach (glob("$dir/*.html") ?: [] as $file) {
            $name = basename($file);
            $moves[$name] = "public/$name";
        }

        return $moves;
    }

    protected function applyMigration(string $migrationFile): int
    {
        $config = $this->parseYaml($migrationFile);
        $dir = $this->directory;
        $isDry = (bool) $this->option('dry-run');

        if ($isDry) {
            $this->writeln('<comment>⚠️  Dry run — no files will be changed.</comment>');
            $this->writeln('');
        }

        if (!$this->option('force') && !$isDry) {
            $this->writeln('');
            $this->writeln('<info>⬆️  Ready to scale your app to Leaf MVC structure.</info>');
            $this->writeln('   This will create directories, move files, and update your entry point.');
            $this->writeln('');

            $confirmed = sprout()->prompt([
                [
                    'type' => 'confirm',
                    'name' => 'proceed',
                    'message' => 'Proceed with migration?',
                    'default' => true,
                ]
            ]);

            if (!($confirmed['proceed'] ?? false)) {
                $this->writeln('<comment>Migration cancelled.</comment>');
                return 0;
            }
        }

        $this->writeln('');
        $this->writeln('<info>⚙️  Applying migration…</info>');
        $this->writeln('');

        $directories = $config['directories'] ?? [];

        foreach ($directories as $relDir) {
            $absDir = "$dir/$relDir";

            if (!is_dir($absDir)) {
                if (!$isDry) {
                    Directory::create($absDir);

                    if (!file_exists("$absDir/.gitkeep")) {
                        file_put_contents("$absDir/.gitkeep", '');
                    }
                }

                $this->writeln("  <info>+</info>  Created directory: $relDir");
            }
        }

        $moves = $config['moves'] ?? [];

        foreach ($moves as $entry) {
            if (empty($entry['from']) || empty($entry['to'])) {
                continue;
            }

            $from = "$dir/{$entry['from']}";
            $to = "$dir/{$entry['to']}";

            if (file_exists($from)) {
                if (!$isDry) {
                    $toDir = dirname($to);

                    if (!is_dir($toDir)) {
                        Directory::create($toDir);
                    }

                    rename($from, $to);
                }

                $this->writeln("  <comment>→</comment>  Moved: {$entry['from']}  →  {$entry['to']}");
            }
        }

        if ($config['extract_routes'] ?? true) {
            $this->extractRoutes($dir, $isDry);
        }

        if ($config['scaffold_controller'] ?? true) {
            $this->scaffoldController($dir, $isDry);
        }

        if ($config['generate_ai_context'] ?? true) {
            $this->generateAiContext($dir, $isDry);
        }

        $packages = $config['install_packages'] ?? [];

        if (!empty($packages) && !$isDry) {
            $pkgList = implode(' ', array_map(fn($p) => "leafs/$p", $packages));
            $this->writeln("  <info>+</info>  Installing packages: $pkgList");
            sprout()->process("composer require $pkgList --ansi")->setTimeout(null)->run();
        }

        $this->writeln('');

        if ($isDry) {
            $this->writeln('<comment>✅  Dry run complete. No files were modified.</comment>');
        } else {
            $this->writeln('<info>🚀  Application scaled to Leaf MVC successfully!</info>');
            $this->writeln('');
            $this->writeln('   Next steps:');
            $this->writeln('     <comment>leaf serve</comment>  — run your upgraded app');
            $this->writeln('     <comment>leaf context</comment> — share context with an external assistant');
        }

        $this->writeln('');

        return 0;
    }

    /**
     * Extract inline routes from index.php into app/routes/index.php,
     * then rewrite index.php to simply load that file.
     */
    protected function extractRoutes(string $dir, bool $isDry): void
    {
        $indexFile = "$dir/index.php";
        $routesFile = "$dir/app/routes/index.php";

        if (!file_exists($indexFile)) {
            return;
        }

        $content = file_get_contents($indexFile);

        $hasInlineRoutes = preg_match('/app\(\)->(get|post|put|patch|delete|any)\s*\(/i', $content);

        if (!$hasInlineRoutes) {
            return;
        }

        $lines = explode("\n", $content);
        $requireLines = [];
        $routeLines = [];
        $appRunLine = '';
        $inRoute = false;
        $braceDepth = 0;
        $buffer = '';

        foreach ($lines as $line) {
            $trimmed = trim($line);

            if ($inRoute) {
                $buffer .= "$line\n";
                $braceDepth += substr_count($line, '{') - substr_count($line, '}');

                if ($braceDepth <= 0) {
                    $routeLines[] = rtrim($buffer);
                    $buffer = '';
                    $inRoute = false;
                }

                continue;
            }

            if (preg_match('/app\(\)-\s*>run\s*\(\s*\)/i', $trimmed)) {
                $appRunLine = $line;
                continue;
            }

            if (preg_match('/app\(\)->(get|post|put|patch|delete|any)\s*\(/i', $trimmed)) {
                $inRoute = true;
                $buffer = "$line\n";
                $braceDepth = substr_count($line, '{') - substr_count($line, '}');

                if ($braceDepth === 0 && str_ends_with(rtrim($line), ';')) {
                    $routeLines[] = rtrim($buffer);
                    $buffer = '';
                    $inRoute = false;
                }
                continue;
            }

            if ($trimmed !== '') {
                $requireLines[] = $line;
            }
        }

        $routesContent = "<?php\n\n" . implode("\n\n", $routeLines) . "\n";

        $bootstrapBlock = implode("\n", $requireLines);
        $newIndex = <<<PHP
<?php

$bootstrapBlock

// Routes
require app_path('routes/index.php');

$appRunLine
PHP;

        if (!$isDry) {
            if (!is_dir("$dir/app/routes")) {
                Directory::create("$dir/app/routes");
            }

            file_put_contents($routesFile, $routesContent);
            file_put_contents($indexFile, trim($newIndex) . "\n");
        }

        $this->writeln("  <info>→</info>  Extracted routes to: app/routes/index.php");
        $this->writeln("  <info>✓</info>  Rewrote index.php to load routes");
    }

    /**
     * Create a basic HomeController stub.
     */
    protected function scaffoldController(string $dir, bool $isDry): void
    {
        $controllerDir = "$dir/app/controllers";
        $controllerFile = "$controllerDir/HomeController.php";

        if (file_exists($controllerFile)) {
            return;
        }

        $stub = <<<PHP
<?php

namespace App\Controllers;

use Leaf\Controller;

class HomeController extends Controller
{
    public function index()
    {
        response()->json(['message' => 'Welcome to Leaf MVC!']);
    }
}
PHP;

        if (!$isDry) {
            if (!is_dir($controllerDir)) {
                Directory::create($controllerDir);
            }

            file_put_contents($controllerFile, trim($stub) . "\n");
        }

        $this->writeln("  <info>+</info>  Scaffolded: app/controllers/HomeController.php");
    }

    /**
     * Generate or update .leaf/context.md with MVC summary.
     */
    protected function generateAiContext(string $dir, bool $isDry): void
    {
        $leafDir = "$dir/.leaf";
        $contextFile = "$leafDir/context.md";

        $appName = basename($dir);
        $modules = $this->detectLeafModules();
        $moduleStr = !empty($modules) ? implode(', ', $modules) : 'leafs/leaf';

        $context = <<<MARKDOWN
# Project Memory: {$appName}

This file contains the shared memory for this project.
All AI assistants working on this project should read this file before making changes.

---

# Project Summary

A Leaf MVC application scaled from a lite app using `leaf up`.

---

# Architecture

## App Type
- **Type**: Leaf MVC (scaled from lite)
- **Entry Point**: index.php → loads app/routes/index.php

## Structure
- `app/controllers/` — Controller classes
- `app/models/`      — Model classes
- `app/views/`       — View templates
- `app/routes/`      — Route definitions
- `app/database/`    — Migrations & seeds
- `public/`          — Public assets & entry point

## Modules
{$moduleStr}

---

# Coding Conventions

- Keep controllers focused and thin.
- Business logic belongs in service classes or models.
- Follow existing naming patterns.

---

# Recent Changes

- Scaled app from lite structure to Leaf MVC using `leaf up`.

---

# Known Decisions

- This is a Leaf MVC app; all important files are in the `app/` directory.
MARKDOWN;

        if (!$isDry) {
            if (!is_dir($leafDir)) {
                Directory::create($leafDir);
            }

            if (!file_exists($contextFile)) {
                file_put_contents($contextFile, trim($context) . "\n");

                $this->writeln("  <info>+</info>  Generated: .leaf/context.md");
            } else {
                $this->writeln("  <comment>~</comment>  Preserved existing: .leaf/context.md");
            }
        } else {
            $this->writeln("  <info>+</info>  Would generate: .leaf/context.md");
        }
    }

    /**
     * Detect whether the current project is already an MVC app.
     */
    protected function isMvcProject(): bool
    {
        $dir = $this->directory;
        return is_dir("$dir/app/controllers")
            && is_dir("$dir/app/routes")
            && (file_exists("$dir/leaf") || file_exists("$dir/leaf.php"));
    }

    /**
     * Read installed Leaf modules from composer.json.
     *
     * @return string[]
     */
    protected function detectLeafModules(): array
    {
        $composerFile = "{$this->directory}/composer.json";

        if (!file_exists($composerFile)) {
            return [];
        }

        $data = json_decode(file_get_contents($composerFile), true) ?? [];
        $require = array_merge($data['require'] ?? [], $data['require-dev'] ?? []);
        $modules = [];

        foreach (array_keys($require) as $pkg) {
            if (str_starts_with($pkg, 'leafs/')) {
                $modules[] = $pkg;
            }
        }

        return $modules;
    }

    /**
     * Minimal YAML parser — handles the simple structure we write ourselves.
     * Supports top-level scalars, list sequences (- item), and nested mappings (- key: val).
     *
     * @return array<string, mixed>
     */
    protected function parseYaml(string $file): array
    {
        $lines = file($file, FILE_IGNORE_NEW_LINES);
        $result = [];
        $currentKey = null;

        foreach ($lines as $line) {
            $stripped = preg_replace('/#.*$/', '', $line);
            $trimmed = trim($stripped);

            if ($trimmed === '') {
                continue;
            }

            if (preg_match('/^([a-z_]+)\s*:\s*(.*)$/i', $trimmed, $m)) {
                $currentKey = $m[1];
                $val = trim($m[2]);

                if ($val === '' || $val === '[]') {
                    $result[$currentKey] = [];
                } elseif ($val === 'true' || $val === 'yes') {
                    $result[$currentKey] = true;
                } elseif ($val === 'false' || $val === 'no') {
                    $result[$currentKey] = false;
                } else {
                    $result[$currentKey] = $val;
                }

                continue;
            }

            if (str_starts_with($trimmed, '- ') && $currentKey !== null) {
                $itemStr = ltrim(substr($trimmed, 2));

                if (preg_match('/^([a-z_]+)\s*:\s*(.+)$/i', $itemStr, $m2)) {
                    $result[$currentKey][] = [$m2[1] => trim($m2[2])];
                } elseif ($itemStr !== '') {
                    $result[$currentKey][] = $itemStr;
                }

                continue;
            }

            if (preg_match('/^\s{2,}([a-z_]+)\s*:\s*(.+)$/i', $trimmed, $m) && $currentKey !== null) {
                $lastIdx = count($result[$currentKey]) - 1;
                if ($lastIdx >= 0 && is_array($result[$currentKey][$lastIdx])) {
                    $result[$currentKey][$lastIdx][$m[1]] = trim($m[2]);
                }
            }
        }

        return $result;
    }
}
