<?php

declare(strict_types=1);

namespace Leaf\Console;

use Leaf\FS\Directory;
use Leaf\Sprout\Command;

/**
 * Leaf Up Command
 *
 * Scales a lite/basic Leaf app into a full MVC structure.
 *
 * First run: generates .leaf/migration.yml describing the planned changes.
 * Second run: applies those changes.
 */
class UpCommand extends Command
{
    protected $signature = 'up
        {--force? : Apply migration without interactive confirmation}
        {--dry-run? : Show what would be changed without modifying any files}';

    protected $description = 'Scale your Leaf app into MVC structure (beta)';

    /** @var string */
    protected string $directory = '';

    protected function handle(): int
    {
        $this->writeln('<comment>leaf up is in beta. Commit your work first, and report anything it gets wrong at https://github.com/leafsphp/cli/issues/new</comment>');
        $this->writeln('');

        $this->directory = getcwd();
        $leafDir = "{$this->directory}/.leaf";
        $migrationFile = "$leafDir/migration.yml";

        if (!file_exists("{$this->directory}/composer.json")) {
            $this->writeln('<error>No composer.json found. Run this command from the root of a Leaf project.</error>');

            return 1;
        }

        if ($this->isMvcProject()) {
            $this->writeln('<info>✅  Your project is already using Leaf MVC structure. Nothing to scale.</info>');

            return 0;
        }

        if (!file_exists($migrationFile)) {
            return $this->generateMigrationPlan($leafDir, $migrationFile);
        }

        return $this->applyMigration($migrationFile);
    }

    protected function generateMigrationPlan(string $leafDir, string $migrationFile): int
    {
        if (!is_dir($leafDir)) {
            Directory::create($leafDir);
        }

        $moves = $this->detectFileMoves();
        $movesYaml = '';

        foreach ($moves as $from => $to) {
            $movesYaml .= "  - from: $from\n    to:   $to\n";
        }

        if (empty($movesYaml)) {
            $movesYaml = "  [] # No existing files detected to move\n";
        }

        $yaml = <<<YAML
# Leaf Migration Plan — generated by `leaf up`
# -----------------------------------------------
# Edit this file before running `leaf up` again to customise what changes are made.
# Paths are relative to the project root.

# ── Directories to create ────────────────────────────────────────────────────
directories:
  - app/controllers
  - app/models
  - app/views
  - app/routes
  - app/database/migrations
  - app/database/seeds
  - public/assets

# ── Files to move ────────────────────────────────────────────────────────────
# from: current path   to: new path
moves:
$movesYaml
# ── Route extraction ─────────────────────────────────────────────────────────
# When true, routes defined inline in index.php are extracted to app/routes/index.php
# and index.php is rewritten to load them.
extract_routes: true

# ── MVC scaffold ─────────────────────────────────────────────────────────────
# When true, a HomeController stub is created under app/controllers.
scaffold_controller: true

# ── AI context ───────────────────────────────────────────────────────────────
# When true, .leaf/CONTEXT.md is generated (or updated) with an MVC summary.
generate_ai_context: true

# ── Composer packages ─────────────────────────────────────────────────────────
# Additional Leaf modules to install as part of the migration.
install_packages: []
YAML;

        file_put_contents($migrationFile, $yaml);

        $this->writeln('');
        $this->writeln('<info>✨  Migration plan generated: .leaf/migration.yml</info>');
        $this->writeln('');
        $this->writeln('   Review or customise the plan, then run <comment>leaf up</comment> again to apply it.');
        $this->writeln('');

        if (!empty($moves)) {
            $this->writeln('   Detected files that will be moved:');
            foreach ($moves as $from => $to) {
                $this->writeln("     <comment>$from</comment>  →  <info>$to</info>");
            }
            $this->writeln('');
        }

        return 0;
    }

    /**
     * Detect obvious file moves for a standard lite Leaf app.
     *
     * @return array<string,string>  from → to pairs
     */
    protected function detectFileMoves(): array
    {
        $moves = [];
        $dir = $this->directory;

        foreach (glob("$dir/*.html") ?: [] as $file) {
            $name = basename($file);
            $moves[$name] = "public/$name";
        }

        return $moves;
    }

    protected function applyMigration(string $migrationFile): int
    {
        $config = $this->parseYaml($migrationFile);
        $dir = $this->directory;
        $isDry = (bool) $this->option('dry-run');

        if ($isDry) {
            $this->writeln('<comment>⚠️  Dry run — no files will be changed.</comment>');
            $this->writeln('');
        }

        if (!$this->option('force') && !$isDry) {
            $this->writeln('');
            $this->writeln('<info>⬆️  Ready to scale your app to Leaf MVC structure.</info>');
            $this->writeln('   This will create directories, move files, and update your entry point.');
            $this->writeln('');

            $confirmed = sprout()->prompt([
                [
                    'type' => 'confirm',
                    'name' => 'proceed',
                    'message' => 'Proceed with migration?',
                    'default' => true,
                ],
            ]);

            if (!($confirmed['proceed'] ?? false)) {
                $this->writeln('<comment>Migration cancelled.</comment>');

                return 0;
            }
        }

        $this->writeln('');
        $this->writeln('<info>⚙️  Applying migration…</info>');
        $this->writeln('');

        $directories = $config['directories'] ?? [];

        foreach ($directories as $relDir) {
            $absDir = "$dir/$relDir";

            if (!is_dir($absDir)) {
                if (!$isDry) {
                    Directory::create($absDir);

                    if (!file_exists("$absDir/.gitkeep")) {
                        file_put_contents("$absDir/.gitkeep", '');
                    }
                }

                $this->writeln("  <info>+</info>  Created directory: $relDir");
            }
        }

        $moves = $config['moves'] ?? [];

        foreach ($moves as $entry) {
            if (empty($entry['from']) || empty($entry['to'])) {
                continue;
            }

            $from = "$dir/{$entry['from']}";
            $to = "$dir/{$entry['to']}";

            if (file_exists($from)) {
                if (!$isDry) {
                    $toDir = dirname($to);

                    if (!is_dir($toDir)) {
                        Directory::create($toDir);
                    }

                    rename($from, $to);
                }

                $this->writeln("  <comment>→</comment>  Moved: {$entry['from']}  →  {$entry['to']}");
            }
        }

        if ($config['extract_routes'] ?? true) {
            $this->extractRoutes($dir, $isDry);
        }

        if ($config['scaffold_controller'] ?? true) {
            $this->scaffoldController($dir, $isDry);
        }

        if ($config['generate_ai_context'] ?? true) {
            $this->generateAiContext($dir, $isDry);
        }

        $packages = $config['install_packages'] ?? [];

        if (!empty($packages) && !$isDry) {
            $pkgList = implode(' ', array_map(fn ($p) => "leafs/$p", $packages));
            $this->writeln("  <info>+</info>  Installing packages: $pkgList");
            sprout()->process("composer require $pkgList --ansi")->setTimeout(null)->run();
        }

        $this->writeln('');

        if ($isDry) {
            $this->writeln('<comment>✅  Dry run complete. No files were modified.</comment>');
        } else {
            $this->writeln('<info>🚀  Application scaled to Leaf MVC successfully!</info>');
            $this->writeln('');
            $this->writeln('   Next steps:');
            $this->writeln('     <comment>leaf serve</comment>  — run your upgraded app');
            $this->writeln('     <comment>leaf context</comment> — share context with an external assistant');
        }

        $this->writeln('');

        return 0;
    }

    /**
     * Extract inline routes from index.php into app/routes/index.php,
     * then rewrite index.php to simply load that file.
     */
    protected function extractRoutes(string $dir, bool $isDry): void
    {
        $indexFile = "$dir/index.php";
        $routesFile = "$dir/app/routes/index.php";

        if (!file_exists($indexFile)) {
            return;
        }

        $content = file_get_contents($indexFile);

        $hasInlineRoutes = preg_match('/app\(\)->(get|post|put|patch|delete|any)\s*\(/i', $content);

        if (!$hasInlineRoutes) {
            return;
        }

        $lines = explode("\n", $content);
        $requireLines = [];
        $routeLines = [];
        $appRunLine = '';
        $inRoute = false;
        $braceDepth = 0;
        $buffer = '';

        foreach ($lines as $line) {
            $trimmed = trim($line);

            if ($inRoute) {
                $buffer .= "$line\n";
                $braceDepth += substr_count($line, '{') - substr_count($line, '}');

                if ($braceDepth <= 0) {
                    $routeLines[] = rtrim($buffer);
                    $buffer = '';
                    $inRoute = false;
                }

                continue;
            }

            if (preg_match('/app\(\)-\s*>run\s*\(\s*\)/i', $trimmed)) {
                $appRunLine = $line;

                continue;
            }

            if (preg_match('/app\(\)->(get|post|put|patch|delete|any)\s*\(/i', $trimmed)) {
                $inRoute = true;
                $buffer = "$line\n";
                $braceDepth = substr_count($line, '{') - substr_count($line, '}');

                if ($braceDepth === 0 && str_ends_with(rtrim($line), ';')) {
                    $routeLines[] = rtrim($buffer);
                    $buffer = '';
                    $inRoute = false;
                }

                continue;
            }

            if ($trimmed !== '') {
                $requireLines[] = $line;
            }
        }

        $routesContent = "<?php\n\n" . implode("\n\n", $routeLines) . "\n";

        $bootstrapBlock = implode("\n", $requireLines);
        $newIndex = <<<PHP
<?php

$bootstrapBlock

// Routes
require app_path('routes/index.php');

$appRunLine
PHP;

        if (!$isDry) {
            if (!is_dir("$dir/app/routes")) {
                Directory::create("$dir/app/routes");
            }

            file_put_contents($routesFile, $routesContent);
            file_put_contents($indexFile, trim($newIndex) . "\n");
        }

        $this->writeln('  <info>→</info>  Extracted routes to: app/routes/index.php');
        $this->writeln('  <info>✓</info>  Rewrote index.php to load routes');
    }

    /**
     * Create a basic HomeController stub.
     */
    protected function scaffoldController(string $dir, bool $isDry): void
    {
        $controllerDir = "$dir/app/controllers";
        $controllerFile = "$controllerDir/HomeController.php";

        if (file_exists($controllerFile)) {
            return;
        }

        $stub = <<<PHP
<?php

namespace App\Controllers;

use Leaf\Controller;

class HomeController extends Controller
{
    public function index()
    {
        response()->json(['message' => 'Welcome to Leaf MVC!']);
    }
}
PHP;

        if (!$isDry) {
            if (!is_dir($controllerDir)) {
                Directory::create($controllerDir);
            }

            file_put_contents($controllerFile, trim($stub) . "\n");
        }

        $this->writeln('  <info>+</info>  Scaffolded: app/controllers/HomeController.php');
    }

    /**
     * Generate or update .leaf/CONTEXT.md with MVC summary.
     */
    protected function generateAiContext(string $dir, bool $isDry): void
    {
        $leafDir = "$dir/.leaf";
        $contextFile = "$leafDir/CONTEXT.md";

        // respect an existing lowercase context file from older setups
        if (!is_file($contextFile) && is_file("$leafDir/context.md")) {
            $contextFile = "$leafDir/context.md";
        }

        $appName = basename($dir);

        $today = date('Y-m-d');

        $context = <<<MARKDOWN
<!-- leaf.context v1 -->

# Project Context

This file is the shared memory for {$appName}. Every AI assistant working here — Claude, Codex, Cursor, or anything else — reads it before making changes and writes useful knowledge back when finished. Treat it as the source of truth for goals, decisions, and conventions.

---

## Working With This File

Read this file before performing any task, together with the project's code and the generated Leaf context. Do not ignore the decisions documented here unless the user explicitly overrides them. When uncertain, prefer preserving existing patterns over introducing new ones.

Format rules, so every agent's edits stay compatible:

1. The first line of this file is its format marker. Never remove or edit it.
2. Sections are `##` headings. Keep them in their current order. Preserve sections you don't recognize — another agent may own them. You may add project-specific sections at the end.
3. A line wrapped in underscores is a placeholder. If it contains `agent:`, it is an instruction to you: act on it, then replace the line with real content (or delete it if it no longer applies).
4. Keep entries to a single line each where possible, so edits from different agents merge cleanly.
5. Never store secrets, keys, or tokens here. Refer to `.env` keys by name only.
6. Do not duplicate mechanical information (routes, models, structure, modules). That lives in the code and in `leaf context`. This file holds only what the code cannot say: goals, decisions, and the reasoning behind them.

When your work is complete:

1. Add a line to Recent Changes: `* YYYY-MM-DD — what changed (key files)`. Newest first, five entries maximum; fold older entries into Known Decisions or delete them.
2. If the Current Goal is done, note it in Recent Changes and replace the goal. If you don't know the next goal, ask the user. Exactly one current goal at a time.
3. Record lasting choices in Known Decisions as `* Decision — reasoning.` A decision without its why gets relitigated by the next agent.
4. Keep this file concise. Summarize instead of appending indefinitely, remove outdated information, and prefer references to files over copying their contents.

---

## Project Summary

A Leaf MVC application, scaled up from a lite app with `leaf up`.

---

## Current Goal

_agent: ask the user what this app is for, then replace this line with the goal. This section always describes the one thing the team is actively working on._

---

## Coding Conventions

* Keep controllers focused and thin.
* Business logic belongs in service classes or models.
* Follow existing naming patterns.

---

## Recent Changes

* {$today} — Scaled from lite structure to Leaf MVC with `leaf up`.

---

## Known Decisions

* This is a Leaf MVC app — all important files are in the `app` directory.

---

## Future Ideas

* _agent: record ideas the user mentions but isn't building yet._
MARKDOWN;

        if (!$isDry) {
            if (!is_dir($leafDir)) {
                Directory::create($leafDir);
            }

            if (!file_exists($contextFile)) {
                file_put_contents($contextFile, trim($context) . "\n");

                $this->writeln('  <info>+</info>  Generated: .leaf/CONTEXT.md');
            } else {
                $this->writeln('  <comment>~</comment>  Preserved existing: ' . str_replace("$dir/", '', $contextFile));
            }
        } else {
            $this->writeln('  <info>+</info>  Would generate: .leaf/CONTEXT.md');
        }
    }

    /**
     * Detect whether the current project is already an MVC app.
     */
    protected function isMvcProject(): bool
    {
        $dir = $this->directory;

        return is_dir("$dir/app/controllers")
            && is_dir("$dir/app/routes")
            && (file_exists("$dir/leaf") || file_exists("$dir/leaf.php"));
    }

    /**
     * Read installed Leaf modules from composer.json.
     *
     * @return string[]
     */
    protected function detectLeafModules(): array
    {
        $composerFile = "{$this->directory}/composer.json";

        if (!file_exists($composerFile)) {
            return [];
        }

        $data = json_decode(file_get_contents($composerFile), true) ?? [];
        $require = array_merge($data['require'] ?? [], $data['require-dev'] ?? []);
        $modules = [];

        foreach (array_keys($require) as $pkg) {
            if (str_starts_with($pkg, 'leafs/')) {
                $modules[] = $pkg;
            }
        }

        return $modules;
    }

    /**
     * Minimal YAML parser — handles the simple structure we write ourselves.
     * Supports top-level scalars, list sequences (- item), and nested mappings (- key: val).
     *
     * @return array<string, mixed>
     */
    protected function parseYaml(string $file): array
    {
        $lines = file($file, FILE_IGNORE_NEW_LINES);
        $result = [];
        $currentKey = null;

        foreach ($lines as $line) {
            $stripped = preg_replace('/#.*$/', '', $line);
            $trimmed = trim($stripped);

            if ($trimmed === '') {
                continue;
            }

            if (preg_match('/^([a-z_]+)\s*:\s*(.*)$/i', $trimmed, $m)) {
                $currentKey = $m[1];
                $val = trim($m[2]);

                if ($val === '' || $val === '[]') {
                    $result[$currentKey] = [];
                } elseif ($val === 'true' || $val === 'yes') {
                    $result[$currentKey] = true;
                } elseif ($val === 'false' || $val === 'no') {
                    $result[$currentKey] = false;
                } else {
                    $result[$currentKey] = $val;
                }

                continue;
            }

            if (str_starts_with($trimmed, '- ') && $currentKey !== null) {
                $itemStr = ltrim(substr($trimmed, 2));

                if (preg_match('/^([a-z_]+)\s*:\s*(.+)$/i', $itemStr, $m2)) {
                    $result[$currentKey][] = [$m2[1] => trim($m2[2])];
                } elseif ($itemStr !== '') {
                    $result[$currentKey][] = $itemStr;
                }

                continue;
            }

            if (preg_match('/^\s{2,}([a-z_]+)\s*:\s*(.+)$/i', $trimmed, $m) && $currentKey !== null) {
                $lastIdx = count($result[$currentKey]) - 1;
                if ($lastIdx >= 0 && is_array($result[$currentKey][$lastIdx])) {
                    $result[$currentKey][$lastIdx][$m[1]] = trim($m[2]);
                }
            }
        }

        return $result;
    }
}
